# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-LDAPapi
version:      3.0.3
version_from: LDAPapi.pm
installdirs:  site
requires:
    Convert::ASN1:                 0.19

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
